# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:

# #############################################################################################################################
# 1. Setting to condition to start action
# #############################################################################################################################

  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# #############################################################################################################################

jobs:
  build:

# #############################################################################################################################
# 2. Setting VM Environment to make artifacts
# #############################################################################################################################

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

# #############################################################################################################################

# #############################################################################################################################
# 3. Make artifacts
# #############################################################################################################################
    
    # 1) Build
    #   a) By gradle 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Check Artifact
      # ${{env.JAVA_HOME}}
      # run: ls -lRs 
      run: |
        pwd
        ls ./build/libs
        
    #   b) By gradle or etc ...
    # 필요시 작성

    # -------------------------------------------------------------------------------------------------------------------------

    #    # 2) Make a container
    #    - name: Docker build 
    #      run: docker build -t spring-boot-cicd .
    #    
    #    - name: Check Docker File
    #      run: |
    #        echo "==============================================="
    #        docker images
    #        echo "==============================================="
    
# #############################################################################################################################

# #############################################################################################################################
# 4. Upload artifacts
# #############################################################################################################################
    
    # 1) Upload as a binary
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: share_file_name
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/*

    # -------------------------------------------------------------------------------------------------------------------------
    
    # 2) Upload as a container
    # 필요시 작성
        
# #############################################################################################################################

  depoly:

# #############################################################################################################################
# 5. Setting VM Environment to depoly artifacts
# #############################################################################################################################

    runs-on: ubuntu-latest
    # needs:build 는 build 과정이 끝난 후 하단의 코드 실행함을 의미 
    needs: build

# #############################################################################################################################

# #############################################################################################################################
# 6. Download artifacts
# #############################################################################################################################

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: share_file_name
    
    - name: Check Download Artifact    
      run: |
        pwd
        ls -lRs
        
# #############################################################################################################################

# #############################################################################################################################
# 7. Deploy artifacts
# #############################################################################################################################
    
    # 1) As a binary
    - name: Sync files with SFTP
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: '35.194.57.195'
        port: 22
        username: ${{ secrets.REMOTE_SSH_ID }}
        password: ${{ secrets.REMOTE_SSH_PASSWORD}}
        localPath: './app.jar'
        remotePath: './artifactory'
    
    # -------------------------------------------------------------------------------------------------------------------------
    
    # 2) As a container
    # 필요시 추가
        
# #############################################################################################################################


# #############################################################################################################################
# 8. Execution a service
# #############################################################################################################################

    - name: Copy to Application By SSH
      uses: appleboy/ssh-action@master 
      with:
        host: 35.194.57.195
        username: ${{ secrets.REMOTE_SSH_ID }}
        password: ${{ secrets.REMOTE_SSH_PASSWORD}}
        port: 22
        #host: ${{ secrets.REMOTE_IP }}
        #username: ${{ secrets.REMOTE_SSH_ID }}
        #key: ${{ secrets.REMOTE_SSH_KEY }} or password: ${{ secrets.REMOTE_SSH_PASSWORD}}
        #port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          echo "For Bianary #############################################################"
          whoami
          echo "For Container ###########################################################"
          pwd

# #############################################################################################################################

    
    
    
    
