# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        
# what made automatically #############################################################
#     - name: Build with Gradle
#       uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
#       with:
#         arguments: build
# #####################################################################################
# what made automatically #############################################################
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
# #####################################################################################
    - name: Check Artifact
      # ${{env.JAVA_HOME}}
      # run: ls -lRs 
      run: |
        pwd
        ls ./build/libs
    
#    - name: Docker build 
#      run: docker build -t spring-boot-cicd .
#    
#    - name: Check Docker File
#      run: |
#        echo "==============================================="
#        docker images
#        echo "==============================================="
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: share_file_name
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/*
    
  depoly:
  
    runs-on: ubuntu-latest
    # needs:build 는 build 과정이 끝난 후 하단의 코드 실행함을 의미 
    needs: build
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: share_file_name
    
    - name: Check Download Artifact    
      run: ls -lRs
    
    - name: Sync files with SFTP
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: '35.194.57.195'
        port: 22
        username: ${{ secrets.REMOTE_SSH_ID }}
        password: ${{ secrets.REMOTE_SSH_PASSWORD}}
        script: pwd
        localPath: './app.jre'
        remotePath: './'
        
    - name: Copy to Application By SSH
      uses: appleboy/ssh-action@master 
      with:
        host: 35.194.57.195
        username: ${{ secrets.REMOTE_SSH_ID }}
        password: ${{ secrets.REMOTE_SSH_PASSWORD}}
        port: 22
        #host: ${{ secrets.REMOTE_IP }}
        #username: ${{ secrets.REMOTE_SSH_ID }}
        #key: ${{ secrets.REMOTE_SSH_KEY }} or password: ${{ secrets.REMOTE_SSH_PASSWORD}}
        #port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          echo "#############################################################"
          whoami
          echo "#############################################################"



    
    
    
    
